name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: current-time-service
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Run Table Creation
      run: npm run db:create

    - name: Run Migration
      run: npm run db:migrate

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # The name of your Azure web app
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} # Set in GitHub Secrets
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  # Path to your packaged application
